config/routes.rb
require 'sidekiq/web'
Meat::Application.routes.draw do

  devise_for :users
  mount ImageReggy::Engine => "/image_reggy"

  root to: 'static_pages#home', layout: 'app/views/layouts/application.html.erb'

  get '/user_guide', to: 'static_pages#user_guide', layout: 'app/views/layouts/no_nav_tree.html.erb'
  get '/faq', to: 'static_pages#faq', layout: 'app/views/layouts/no_nav_tree.html.erb'
  mount Sidekiq::Web, at: "/sidekiq"

  post 'captures/move'
  post 'captures/merge'
  post 'historic_captures/move'
  post 'historic_captures/merge'
  post 'capture_images/move'
  post 'location_images/move'
  post 'metadata_files/move'
  post 'survey_seasons/move'

  resources :location_images

  resources :surveyors do
    resources :surveys
  end
  resources :surveys, except: :new do
    resources :survey_seasons
    resources :captures
    resources :historic_captures
  end
  resources :stations, except: :new do
    resources :visits
    resources :historic_visits
    resources :captures
  end
  resources :survey_seasons, except: :new do
    resources :stations
    resources :captures
    resources :historic_captures
    resources :glass_plate_listings
    resources :maps
  end

  resources :captures, except: :new do
    resources :capture_images
    member do
      get 'comparisons'
      get 'overlays'
    end
  end

  resources :projects do
    resources :stations
    resources :captures
    resources :historic_captures
  end

  resources :historic_captures do
    member do
      get 'comparisons'
      get 'overlays'
    end
  end

  get 'application/update_historic_captures', as: 'update_historic_captures'
  get 'application/treedata', to: 'application#treedata', as: 'treedata'
  get 'filters/:filter_name', to: 'application#filters', as: "filter"

  resources :bulk_import_forms
  get 'settings', to: 'settings_forms#edit'
  patch 'settings', to: 'settings_forms#update'
  post 'settings', to: 'settings_forms#update'
  get 'publisher', to: 'publisher_forms#edit'
  patch 'publisher', to: 'publisher_forms#update'
  post 'publisher', to: 'publisher_forms#update'

  resources :visits, except: :new do
    resources :captures
  end
  resources :locations, except: :new do
    resources :captures
  end
  resources :keywords
  resources :participants

  resources :historic_visits, except: :new
  resources :capture_images, except: :new do
    member do
      get 'download'
      get 'open'
      resource 'master_creation', controller: 'master_creation', as: 'master_creation', only: [:new, :create]
    end
  end

  resources :location_images, except: :new do
    member do
      get "download"
      get "open"
    end
  end

  get "/field_note/:id/open" => "field_notes#open"
  get "/field_note/:id/download" => "field_notes#download"
  get "/metadata_file/:id/open" => "metadata_files#open"
  get "/metadata_file/:id/download" => "metadata_files#download"

  get "/stations/:id/open_old" => "stations#open_old"

  get "/surveys/:id/open_metadata_folder" => "surveys#open_metadata_folder"
  get "/survey_seasons/:id/open_metadata_folder" => "survey_seasons#open_metadata_folder"
  get "/projects/:id/open_metadata_folder" => "projects#open_metadata_folder"

end

app/controllers/publisher_forms_controller.rb
class PublisherFormsController < ApplicationController
  load_and_authorize_resource

  def edit
    @publisher_form = PublisherForm.new
  end

  def update
    @publisher_form = PublisherForm.new
    if @publisher_form.submit
      flash[:success] = "Successfully initiated publish update"
    end
    render 'edit'
  end

end

app/views/publisher_forms/edit.html.erb
<% disable_publish = @publisher_form.update_criteria_captures.blank? && @publisher_form.update_criteria_historic_captures.blank? %>
<div class="submenu_bar">
  <%= Menu.new("Publisher",:boostrap).to_html %>
</div>
<div class='data-pane-body'>
<div class='publisher_intro'>
<p>The publisher assists in publishing MLP content to our public facing website. When the 'Update Published Content' button is pressed, system content will be compared with the current update criteria setting for each object type that can be published publically (currently only Captures, Historic Captures, and Location Images).
</p>
<p> The 'Published Content Overview' section gives a brief overview of the percentage of objects currently published/unpublished in addition to showing how many objects will be published/unpublished if an update is executed with the current settings.
<p>
<p> Publishing a capture/historic capture/location image requires that are server generates smaller versions of the images and uploads them to a remote location. This process can be fairly costly in turns of computation, especially when large batches of images need to be published. When you press the 'Update Published Content' button, each object publication is pushed to a background job, meaning that you can continue to use MEAT while the publication process occurs. This also means that publication is for all intended objects is not instanteous. An overview of the jobs being processed and queued for processing can be seen in the 'Published Content Overview' section. It is advisable to not update publisher when jobs are currently being processed or queued for processing.
</p>
</div>
<h4>Published Content Overview</h4>
<div class='well' id='published_content_overview'>
  <div id='capture_legend'></div>
  <div class='row-fluid'>
    <div class='span6'>
      <span class='content_overview_object_title'>Captures(<%= @publisher_form.captures_data.inject(0){|m,v|m+=v[:value]}%>)</span>
      <%= content_tag :canvas, "", id: 'capture_chart', width: '150', height: '150', data: { content: @publisher_form.captures_data } %>
    </div>
    <div class='span6'>
      <span class='content_overview_object_title'>Historic Captures(<%= @publisher_form.historic_captures_data.inject(0){|m,v|m+=v[:value]}%>)</span>
      <%= content_tag :canvas, "", id: 'historic_capture_chart', width: '150', height: '150', data: { content: @publisher_form.historic_captures_data } %>
    </div>
  </div>
  <div><span class='job_title'>Jobs Currently Processing</span>: <span class='job_count'><%= @publisher_form.jobs_processing %></span></div>
  <div><span class='job_title'>Jobs Currently Queued</span>: <span class='job_count'><%= @publisher_form.jobs_queued %></span></div>
</div>
<h4>Current Settings</h4>
<div class='well' id='publisher_current_settings'>
    <p>Update Criteria For Captures: <%= @publisher_form.criteria_captures_human_name %></p>
    <p>Update Criteria For Historic Captures: <%= @publisher_form.criteria_historic_captures_human_name %></p>
    <p id='missing_publisher_settings'>'<%= link_to "Go to Settings", settings_path %>' to configure update criteria.</p>
</div>
<%= simple_form_for @publisher_form, url: publisher_path do |f| %>
  <%= f.error_messages %>

  <%= f.button :submit, "Update Published Content", disabled: disable_publish %>
<% end %>
</div>