config/routes.rb
require 'sidekiq/web'
Meat::Application.routes.draw do

  devise_for :users
  mount ImageReggy::Engine => "/image_reggy"

  root to: 'static_pages#home', layout: 'app/views/layouts/application.html.erb'

  get '/user_guide', to: 'static_pages#user_guide', layout: 'app/views/layouts/no_nav_tree.html.erb'
  get '/faq', to: 'static_pages#faq', layout: 'app/views/layouts/no_nav_tree.html.erb'
  mount Sidekiq::Web, at: "/sidekiq"

  post 'captures/move'
  post 'captures/merge'
  post 'historic_captures/move'
  post 'historic_captures/merge'
  post 'capture_images/move'
  post 'location_images/move'
  post 'metadata_files/move'
  post 'survey_seasons/move'

  resources :location_images

  resources :surveyors do
    resources :surveys
  end
  resources :surveys, except: :new do
    resources :survey_seasons
    resources :captures
    resources :historic_captures
  end
  resources :stations, except: :new do
    resources :visits
    resources :historic_visits
    resources :captures
  end
  resources :survey_seasons, except: :new do
    resources :stations
    resources :captures
    resources :historic_captures
    resources :glass_plate_listings
    resources :maps
  end

  resources :captures, except: :new do
    resources :capture_images
    member do
      get 'comparisons'
      get 'overlays'
    end
  end

  resources :projects do
    resources :stations
    resources :captures
    resources :historic_captures
  end

  resources :historic_captures do
    member do
      get 'comparisons'
      get 'overlays'
    end
  end

  get 'application/update_historic_captures', as: 'update_historic_captures'
  get 'application/treedata', to: 'application#treedata', as: 'treedata'
  get 'filters/:filter_name', to: 'application#filters', as: "filter"

  resources :bulk_import_forms
  get 'settings', to: 'settings_forms#edit'
  patch 'settings', to: 'settings_forms#update'
  post 'settings', to: 'settings_forms#update'
  get 'publisher', to: 'publisher_forms#edit'
  patch 'publisher', to: 'publisher_forms#update'
  post 'publisher', to: 'publisher_forms#update'

  resources :visits, except: :new do
    resources :captures
  end
  resources :locations, except: :new do
    resources :captures
  end
  resources :keywords
  resources :participants

  resources :historic_visits, except: :new
  resources :capture_images, except: :new do
    member do
      get 'download'
      get 'open'
      resource 'master_creation', controller: 'master_creation', as: 'master_creation', only: [:new, :create]
    end
  end

  resources :location_images, except: :new do
    member do
      get "download"
      get "open"
    end
  end

  get "/field_note/:id/open" => "field_notes#open"
  get "/field_note/:id/download" => "field_notes#download"
  get "/metadata_file/:id/open" => "metadata_files#open"
  get "/metadata_file/:id/download" => "metadata_files#download"

  get "/stations/:id/open_old" => "stations#open_old"

  get "/surveys/:id/open_metadata_folder" => "surveys#open_metadata_folder"
  get "/survey_seasons/:id/open_metadata_folder" => "survey_seasons#open_metadata_folder"
  get "/projects/:id/open_metadata_folder" => "projects#open_metadata_folder"

end

app/views/visits/_form.html.erb
<%= simple_form_for visit, :html => { :class => 'visit_form my_container' }  do |f| %>
		<%= f.error_messages %>
		<%= f.hidden_field :station_id, value: @visit.station.id%>
		<%= f.input :date, start_year: 1826, end_year: Time.now.year, input_html: { class: 'input-small'} %>
		<%= f.input :start_time, include_blank: true, input_html: { class: 'input-mini'}%>
		<%= f.input :finish_time, include_blank: true, input_html: { class: 'input-mini'}%>
		<%= f.association :photographers, collection: Participant.order(:given_names).map { |p| [p.given_names+' '+p.last_name, p.id.to_s]}, label: 'Photographer(s) (<a href="#photographer_new_modal" data-toggle="modal">Create New Participant</a>)'.html_safe %>
		<%= f.association :fn_authors, collection: Participant.order(:given_names).map { |p| [p.given_names+' '+p.last_name, p.id.to_s]}, label: 'Field note author(s) (<a href="#fn_author_new_modal" data-toggle="modal">Create New Participant</a>)'.html_safe  %>
		<%= f.association :hiking_party_participants, collection: Participant.order(:given_names).collect{ |p| [p.given_names+" "+p.last_name, p.id]}, label: 'Hiking Party (<a href="#hiking_party_participant_new_modal" data-toggle="modal">Create New Participant</a>)'.html_safe %>
		<%= f.association :keywords, collection: Keyword.order(:keyword).collect{ |k| [k.keyword, k.id]}, label: 'Keyword (<a href="#keyword_new_modal" data-toggle="modal">Create New Keyword</a>)'.html_safe %>
		<%= f.input :pilot %>
		<%= f.input :rw_call_sign %>
		<%= f.input :visit_narrative, input_html: { rows: 8, class: 'span10'} %>
		<%= f.input :illustration %>
		<%= f.input :weather_narrative, input_html: { rows: 8, class: 'span10'} %>
		<div class='row-fluid'>
			<div class='span3'>
				<p><%= f.object.class.human_attribute_name(:weather_temp) %></p>
				<div class='input-append'><%= f.input_field :weather_temp, class: 'input-mini' %><span class='add-on'>&deg;</span></div>
			</div>
			<div class='span3'>
				<p><%= f.object.class.human_attribute_name(:weather_ws) %></p>
				<div class='input-append'><%= f.input_field :weather_ws, class: 'input-mini' %><span class='add-on'>km/h</span></div>
			</div>
			<div class='span3'>
				<p><%= f.object.class.human_attribute_name(:weather_gs) %></p>
				<div class='input-append'><%= f.input_field :weather_gs, class: 'input-mini' %><span class='add-on'>km/h</span></div>
			</div>
		</div>
		<div class='row-fluid'>
			<div class='span3'>
				<p><%= f.object.class.human_attribute_name(:weather_rh) %></p>
				<div class='input-append'><%= f.input_field :weather_rh, class: 'input-mini' %><span class='add-on'>%</span></div>
			</div>
			<div class='span3'>
				<p><%= f.object.class.human_attribute_name(:weather_wb) %></p>
				<div class='input-append'><%= f.input_field :weather_wb, class: 'input-mini' %><span class='add-on'>&deg;C</span></div>
			</div>
			<div class='span3'>
				<p><%= f.object.class.human_attribute_name(:weather_pressure) %></p>
				<div class='input-append'><%= f.input_field :weather_pressure, class: 'input-mini' %><span class='add-on'>hPa</span></div>
			</div>
		</div>
		<%= render 'field_notes/field_note_fields_table', f: f %>
		<%= f.input :fn_physical_location, input_html: { class: "input-xlarge", placeholder: "Book 1, 2008, pg. 12-14 or Binder 1, 2009" } %>
		<%= f.input :fn_transcription_comment, input_html: { rows: 8, class: 'span10'} %>
		<%= render 'metadata_files/metadata_file_fields_table', f:f %>
		<h2> Locations </h2>
		<div id="nested_locations">
		<%= f.fields_for :locations do |builder| %>
			<%= render "locations/location_fields", :f => builder %>
		<% end %>

		<%= link_to_add_fields "Add location", f,  :locations %>
		</div>
		<p></p>
		<p><%= f.button :submit, "Submit"%></p>
<% end %>
<%= render 'keywords/new_modal', keyword: @keyword %>
<%= render 'participants/new_modal', participant: @participant, participant_type: "photographer" %>
<%= render 'participants/new_modal', participant: @participant, participant_type: "fn_author" %>
<%= render 'participants/new_modal', participant: @participant, participant_type: "hiking_party_participant" %>

app/views/visits/_show_view_header.html.erb
<%= content_tag :div, class: "submenu_bar" do  %>
  <%=
    menu = Menu.new("Visit",:boostrap)
    if current_user.try(:admin)
      menu.add link: link_to("<span class='icomoon-pencil submenu_icon' title='Edit'></span>Edit".html_safe, edit_visit_path(@visit.id), class: 'edit_link')
      submenu = Menu.new("<span class='icomoon-menu submenu_icon' title='More Options'></span>", :sub)
      submenu.add link: link_to("<span class='icomoon-plus submenu_icon icon_next_to_word' title='Add Unsorted Capture'></span>Add Unsorted Capture".html_safe, new_visit_capture_path(@visit.id))
      submenu.add link: link_to("<span class='icomoon-add-to-list submenu_icon icon_next_to_word' title='Bulk Capture Import'></span>Bulk Capture Import".html_safe, new_bulk_import_form_path(parent_id: @visit.id, parent_class: @visit.class.name, association: "unsorted_captures"))
      menu.add submenu
      menu.add_delete(url_for(@visit), "Are you sure you want to delete this visit and its locations, captures, and capture images?")
    end
    menu.to_html
    %>
<% end %>

app/views/visits/edit.html.erb
<%= content_tag :div, class: "submenu_bar" do  %>
  <%= Menu.new("Edit Visit",:boostrap).to_html %>
<% end %>
<div class='data-pane-body'>
  <%= breadcrumb_div(@visit, separator: "/", with_self: true).html_safe %>
  <%= render "form", visit: @visit %>
</div>

app/views/visits/new.html.erb
<%= content_tag :div, class: "submenu_bar" do  %>
<%= Menu.new("Add New Visit",:boostrap).to_html %>
<% end %>
<div class='data-pane-body'>
<%= render "form", visit: @visit %>
</div>