config/routes.rb
require 'sidekiq/web'
Meat::Application.routes.draw do

  devise_for :users
  mount ImageReggy::Engine => "/image_reggy"

  root to: 'static_pages#home', layout: 'app/views/layouts/application.html.erb'

  get '/user_guide', to: 'static_pages#user_guide', layout: 'app/views/layouts/no_nav_tree.html.erb'
  get '/faq', to: 'static_pages#faq', layout: 'app/views/layouts/no_nav_tree.html.erb'
  mount Sidekiq::Web, at: "/sidekiq"

  post 'captures/move'
  post 'captures/merge'
  post 'historic_captures/move'
  post 'historic_captures/merge'
  post 'capture_images/move'
  post 'location_images/move'
  post 'metadata_files/move'
  post 'survey_seasons/move'

  resources :location_images

  resources :surveyors do
    resources :surveys
  end
  resources :surveys, except: :new do
    resources :survey_seasons
    resources :captures
    resources :historic_captures
  end
  resources :stations, except: :new do
    resources :visits
    resources :historic_visits
    resources :captures
  end
  resources :survey_seasons, except: :new do
    resources :stations
    resources :captures
    resources :historic_captures
    resources :glass_plate_listings
    resources :maps
  end

  resources :captures, except: :new do
    resources :capture_images
    member do
      get 'comparisons'
      get 'overlays'
    end
  end

  resources :projects do
    resources :stations
    resources :captures
    resources :historic_captures
  end

  resources :historic_captures do
    member do
      get 'comparisons'
      get 'overlays'
    end
  end

  get 'application/update_historic_captures', as: 'update_historic_captures'
  get 'application/treedata', to: 'application#treedata', as: 'treedata'
  get 'filters/:filter_name', to: 'application#filters', as: "filter"

  resources :bulk_import_forms
  get 'settings', to: 'settings_forms#edit'
  patch 'settings', to: 'settings_forms#update'
  post 'settings', to: 'settings_forms#update'
  get 'publisher', to: 'publisher_forms#edit'
  patch 'publisher', to: 'publisher_forms#update'
  post 'publisher', to: 'publisher_forms#update'

  resources :visits, except: :new do
    resources :captures
  end
  resources :locations, except: :new do
    resources :captures
  end
  resources :keywords
  resources :participants

  resources :historic_visits, except: :new
  resources :capture_images, except: :new do
    member do
      get 'download'
      get 'open'
      resource 'master_creation', controller: 'master_creation', as: 'master_creation', only: [:new, :create]
    end
  end

  resources :location_images, except: :new do
    member do
      get "download"
      get "open"
    end
  end

  get "/field_note/:id/open" => "field_notes#open"
  get "/field_note/:id/download" => "field_notes#download"
  get "/metadata_file/:id/open" => "metadata_files#open"
  get "/metadata_file/:id/download" => "metadata_files#download"

  get "/stations/:id/open_old" => "stations#open_old"

  get "/surveys/:id/open_metadata_folder" => "surveys#open_metadata_folder"
  get "/survey_seasons/:id/open_metadata_folder" => "survey_seasons#open_metadata_folder"
  get "/projects/:id/open_metadata_folder" => "projects#open_metadata_folder"

end

app/views/capture_images/_capture_image_fields.html.erb
<fieldset>
<div class='row-fluid' id="<%= f.object.image_secure_token %>" >
<% if f.object.new_record? %>
  <div class='span4'><%= f.input :image, as: :file, label: false, wrapper_html: {class: 'span3'}, input_html: {class: "image"} %><%= f.hidden_field :image_cache %></div>
  <div class='span4'><%= f.input :image_state, as: :select, collection: IMAGE_STATES.map{|s|[s,s]}, label: false ,wrapper_html: {class: 'span3'}, input_html: { class: 'image_state'}%></div>
  <div class='span2'><%= f.input :remote, as: :boolean, label: false,wrapper_html: {class: 'span3'}, input_html: {class: "remote"} %></div>
  <div class='span2'><%= f.hidden_field :_destroy %><%= link_to "Remove", '#', class: "remove_fields" %></div>
<% else %>
  <div class='span4'>
      <% if !f.object.image.nil? && f.object.valid? %>
        <%= link_to_local_file f.object.display_name, f.object.image.file.path  %>
      <% else %>
        <%= f.object.display_name %>
      <% end %>
      <% if !f.object.x_dim.nil? && !f.object.y_dim.nil? %></br>
        <%= f.object.x_dim.to_s+'x'+f.object.y_dim.to_s  %>
      <% end %>
      <% if !f.object.file_size.nil? %></br>
        <%= number_to_human_size(f.object.file_size) %>
      <% end %>
  </div>
  <div class='span4'>
    <%= f.input :image_state, as: :select, collection: IMAGE_STATES.map{|s|[s,s]}, selected: f.object.image_state, label: false, input_html: { class: 'image_state'}, disabled: !f.object.file_present?, hint: (!f.object.file_present? ? "Image has most likely been moved or deleted outside of this application. Please move back to #{f.object.image.file.path} if possible." : "")%>
  </div>
  <div class='span2'>
    <%= f.input :remote, as: :boolean, :input_html => { :checked => f.object.image_remote.blank? ? '' : 'checked', class: "remote" } ,  label: false,  wrapper_html: {class: 'span3'}, disabled: !f.object.file_present? %>
  </div>
  <div class='span2'>
    <%= f.check_box :_destroy, class: 'delete_check_box', input_html: {class: "image_delete"} %>
  </div>
<% end %>
</div>
</fieldset>

app/views/capture_images/_show_view_header.html.erb
<%= content_tag :div, class: "submenu_bar" do  %>
  <%=
      menu = Menu.new("Capture Image",:boostrap)
      menu.add link: link_to("<span class='icomoon-images submenu_icon' title='Master'></span>Master Capture Image".html_safe, new_master_creation_path, {:data => {skip_pjax: true}}), display: @capture_image.file_present? && current_user.try(:admin) && @capture_image.captureable_type=="Capture"
      menu.add link: link_to("<span class='icomoon-box-add submenu_icon' title='Download'></span>Download".html_safe, download_capture_image_path, {:data => {skip_pjax: true}}), display: @capture_image.file_present?
      menu.add link: link_to("<span class='icomoon-eye submenu_icon' title='Open'></span>Open".html_safe, open_capture_image_path, data: { confirm: "IMPORTANT! Never change the name of an opened file via an external application. If you are making major changes to the file, it is probably best to use the 'Save As' option in the external application and add the file as a new capture image of the capture." }, remote: true), display: @capture_image.file_present? && current_user.try(:admin) && client_on_server?
      menu.add_delete(url_for(@capture_image), "Are you sure you want to delete this capture image?") if current_user.try(:admin)
      menu.to_html
   %>
<% end %>