config/routes.rb
require 'sidekiq/web'
Meat::Application.routes.draw do

  devise_for :users
  mount ImageReggy::Engine => "/image_reggy"

  root to: 'static_pages#home', layout: 'app/views/layouts/application.html.erb'

  get '/user_guide', to: 'static_pages#user_guide', layout: 'app/views/layouts/no_nav_tree.html.erb'
  get '/faq', to: 'static_pages#faq', layout: 'app/views/layouts/no_nav_tree.html.erb'
  mount Sidekiq::Web, at: "/sidekiq"

  post 'captures/move'
  post 'captures/merge'
  post 'historic_captures/move'
  post 'historic_captures/merge'
  post 'capture_images/move'
  post 'location_images/move'
  post 'metadata_files/move'
  post 'survey_seasons/move'

  resources :location_images

  resources :surveyors do
    resources :surveys
  end
  resources :surveys, except: :new do
    resources :survey_seasons
    resources :captures
    resources :historic_captures
  end
  resources :stations, except: :new do
    resources :visits
    resources :historic_visits
    resources :captures
  end
  resources :survey_seasons, except: :new do
    resources :stations
    resources :captures
    resources :historic_captures
    resources :glass_plate_listings
    resources :maps
  end

  resources :captures, except: :new do
    resources :capture_images
    member do
      get 'comparisons'
      get 'overlays'
    end
  end

  resources :projects do
    resources :stations
    resources :captures
    resources :historic_captures
  end

  resources :historic_captures do
    member do
      get 'comparisons'
      get 'overlays'
    end
  end

  get 'application/update_historic_captures', as: 'update_historic_captures'
  get 'application/treedata', to: 'application#treedata', as: 'treedata'
  get 'filters/:filter_name', to: 'application#filters', as: "filter"

  resources :bulk_import_forms
  get 'settings', to: 'settings_forms#edit'
  patch 'settings', to: 'settings_forms#update'
  post 'settings', to: 'settings_forms#update'
  get 'publisher', to: 'publisher_forms#edit'
  patch 'publisher', to: 'publisher_forms#update'
  post 'publisher', to: 'publisher_forms#update'

  resources :visits, except: :new do
    resources :captures
  end
  resources :locations, except: :new do
    resources :captures
  end
  resources :keywords
  resources :participants

  resources :historic_visits, except: :new
  resources :capture_images, except: :new do
    member do
      get 'download'
      get 'open'
      resource 'master_creation', controller: 'master_creation', as: 'master_creation', only: [:new, :create]
    end
  end

  resources :location_images, except: :new do
    member do
      get "download"
      get "open"
    end
  end

  get "/field_note/:id/open" => "field_notes#open"
  get "/field_note/:id/download" => "field_notes#download"
  get "/metadata_file/:id/open" => "metadata_files#open"
  get "/metadata_file/:id/download" => "metadata_files#download"

  get "/stations/:id/open_old" => "stations#open_old"

  get "/surveys/:id/open_metadata_folder" => "surveys#open_metadata_folder"
  get "/survey_seasons/:id/open_metadata_folder" => "survey_seasons#open_metadata_folder"
  get "/projects/:id/open_metadata_folder" => "projects#open_metadata_folder"

end

app/views/surveys/_form.html.erb
<%= simple_form_for survey, :html => { :class => 'visit_form my_container' }  do |f| %>
		<%= f.error_messages %>
		<%= f.hidden_field :surveyor_id, value: @survey.surveyor.id%>
		<%= f.input :name %>
		<%= f.input :historical_map_sheet %>
		<p><%= f.button :submit, "Submit"%></p>
<% end %>

app/views/surveys/_show_view_header.html.erb
<%= content_tag :div, class: "submenu_bar" do  %>
    <%=
    menu = Menu.new("Survey",:boostrap)
    if current_user.try(:admin)
      menu.add link: link_to("<span class='icomoon-pencil submenu_icon' title='Edit'></span>Edit".html_safe, edit_survey_path(@survey.id), class: 'edit_link')
      menu.add link: link_to("<span class='icomoon-plus submenu_icon icon_next_to_word' title='Add Survey Season'></span>Add Survey Season".html_safe, new_survey_survey_season_path(@survey))
      submenu = Menu.new("<span class='icomoon-menu submenu_icon' title='More Options'></span>", :sub)
      submenu.add link: link_to("<span class='icomoon-plus submenu_icon icon_next_to_word' title='Add Unsorted Capture'></span>Add Unsorted Capture".html_safe, new_survey_capture_path(@survey))
      submenu.add link: link_to("<span class='icomoon-plus submenu_icon icon_next_to_word' title='Add Unsorted Historic Capture'></span>Add Unsorted Historic Capture".html_safe, new_survey_historic_capture_path(@survey))
      submenu.add link: link_to("<span class='icomoon-add-to-list submenu_icon icon_next_to_word' title='Bulk Capture Import'></span>Bulk Capture Import".html_safe, new_bulk_import_form_path(parent_id: @survey.id, parent_class: @survey.class.name, association: "unsorted_captures"))
      submenu.add link: link_to("<span class='icomoon-add-to-list submenu_icon icon_next_to_word' title='Bulk Historic Capture Import'></span>Bulk Historic Capture Import".html_safe, new_bulk_import_form_path(parent_id: @survey.id, parent_class: @survey.class.name, association: "unsorted_hcaptures"))
      submenu.add link: link_to("<span class='icomoon-folder-open submenu_icon icon_next_to_word' title='Browse Metadata Folder'></span>Browse Metadata Folder".html_safe, "/surveys/#{@survey.id}/open_metadata_folder", remote: true), display: client_on_server?
      menu.add submenu
      if can? :destroy, @survey
        menu.add_delete(url_for(@survey), "Are you sure you want to delete this survey and its survey seasons, stations, visits, locations, captures, and capture images?")
      end
    end
    menu.to_html
    %>
<% end %>

app/views/surveys/edit.html.erb
<%= content_tag :div, class: "submenu_bar" do  %>
<%= Menu.new("Edit Survey",:boostrap).to_html %>
<% end %>
<div class='data-pane-body'>
  <%= breadcrumb_div(@survey, separator: "/", with_self: true).html_safe %>
<%= render "form", survey: @survey %>
</div>

app/views/surveys/new.html.erb
<%= content_tag :div, class: "submenu_bar" do  %>
<%= Menu.new("Add New Survey",:boostrap).to_html %>
<% end %>
<div class='data-pane-body'>
<%= render "form", survey: @survey %>
</div>